apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: elephant-pitr
  namespace: debug
spec:
  dataSource:
    postgresCluster:
      clusterNamespace: postgres-operator
      clusterName: elephant
      repoName: repo1
      options: 
      - --type=time 
      - --target="2022-04-12 02:25:07+00"
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.2-0
  postgresVersion: 14
  instances:
    - dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
        # storageClassName: standard

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-1
      global:
      ## keep full backup for 2 days
        repo1-retention-full: "2"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        schedules:
        ##  take a full backup very 11Min and take incremental backups every 6Min
          full: "*/11 * * * *"
          incremental: "*/6 * * * *"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
            # storageClassName: standard